const translate = {
  "Home": "گھر",
  "How It Works": "How It Works",
  "Pricing": "Pricing",
  "FAQ's": "FAQ's",
  "Benifits": "Benifits",
  "login": "login",
  "Improve customer experience and reduce cost at your Restaurant" : "Improve customer experience and reduce cost at your Restaurant",
  "your customers can order from their table by simply scanning QR code and": "your customers can order from their table by simply scanning QR code and",
  "ordering without the need for a mobile app" : "ordering without the need for a mobile app",
  "Hospitality is changing. Your customers can now tap scan a smart QR code with their own device, order food and drink, pay and either have the order brought to their table or receive an sms notifying them that the order is ready" : "Hospitality is changing. Your customers can now tap scan a smart QR code with their own device, order food and drink, pay and either have the order brought to their table or receive an sms notifying them that the order is ready",
  "SCAN, ORDER & PAY": "SCAN, ORDER & PAY",
  "Your customers can order from their table by": "Your customers can order from their table by",
  "simply scanning a QR code": "simply scanning a QR code",
  "Try it for free": "Try it for free",
  "View Plans": "View Plans",
  "Mobile scan code order": "Mobile scan code order",
  "Turn on the scan QR code function in any software. Including skip-the-line, online ordering, self-service plus dishes, changing table, call attendant and other functions": "Turn on the scan QR code function in any software. Including skip-the-line, online ordering, self-service plus dishes, changing table, call attendant and other functions",
  "Register Now": "Register Now",
  "Login to your account": "Login to your account",
  "Phone Number": "Phone Number",
  "Password": "Password",
  "forgot password ?": "forgot password ?",
  "Get OTP": "Get OTP",
  "SEND": "SEND",
  "Enter your email": "Enter your email",
  "LOGIN": "LOGIN",
  "Don’t have an account?": "Don’t have an account?",
  "Register Here": "Register Here",
  "THANK YOU !": "THANK YOU !",
  "for your registration, your account will be activated in less than 24 hours": "for your registration, your account will be activated in less than 24 hours",
  "Register Yourself": "Register Yourself",
  "Your Name": "Your Name",
  "Already have an account?": "Already have an account?",
  "REGISTER": "REGISTER",
  "Email": "Email",
  "Please enter valid email": "Please enter valid email",
  "Please enter min 6 chars": "Please enter min 6 chars",
  "Please enter valid mobile number": "Please enter valid mobile number",
  "Please enter valid name": "Please enter valid name",
  "Repeated password is not same": "Repeated password is not same",
  "Create New Password": "Create New Password",
  "Enter Password": "Enter Password",
  "Repeat Password": "Repeat Password",
  "Reset Password": "Reset Password",
  "Dashboard": "Dashboard",
  "Restaurant": "Restaurant",
  "Orders": "Orders",
  "Menu Management": "Menu Management",
  "Manage QR": "Manage QR",
  "Analytics": "Analytics",
  "You have": "You have",
  "new notifications": "new notifications",
  "Logout": "Logout",
  "Today’s Revenue": "Today’s Revenue",
  "Today’s Orders": "Today’s Orders",
  "Total Revenue Last 7 Days": "Total Revenue Last 7 Days",
  "$": "$",
  "Revenue": "Revenue",
  "Total Orders Last 7 Days": "Total Orders Last 7 Days",
  "Order": "Order",
  "Jan": "Jan",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Apr",
  "May": "May",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Aug",
  "Sep": "Sep",
  "Oct": "Oct",
  "Nov": "Nov",
  "Dec": "Dec",
  "It should be valid" : "It should be valid",
  "Category Name (English)" : "Category Name (English)",
  "Enter category name": "Enter category name",
  "Category Name (Arabic)" : "Category Name (Arabic)",
  "Submit" : "Submit",
  "Update" : "Update",
  "Accept": "Accept",
  "Accepted" : "Accepted",
  "Complete" : "Complete",
  "Cancelled" : "Cancelled",
  "Date/Time" : "Date/Time",
  "Type" : "Type",
  "Order Number" : "Order Number",
  "Table No" : "Table No",
  "Payment Type": "Payment Type",
  "Status":"Status",
  "Pay" : "Pay",
  "Details" : "Details",
  "dinein": "dinein",
  "dineout": "dineout",
  "Cancel Order" : "Cancel Order",
  "Quantity": "Quantity",
  "Dish": "Dish",
  "Addons": "Addons",
  "Price": "Price",
  "Sub Total": "Sub Total",
  "Tax": "Tax",
  "Total": "Total",
  "Payment Method": "Payment Method",
  "Comments": "Comments",
  "Start Date": "Start Date",
  "End Date": "End Date",
  "Total Revenue" : "Total Revenue",
  "Total Orders" : "Total Orders",
  "Your restaurant is not approved to generete qr code" : "Your restaurant is not approved to generete qr code",
  "Generate QR code" : "Generate QR code",
  "Table Number" : "Table Number",
  "Enter Table No": "Enter Table No",
  "Text": "Text",
  "Add text on QR": "Add text on QR",
  "Text Color": "Text Color",
  "Enter text color": "Enter text color",
  "Text Size" : "Text Size",
  "Enter text size": "Enter text size",
  "Layout Size": "Layout Size",
  "Enter layout size" : "Enter layout size",
  "Background Color": "Background Color",
  "QR Color": "QR Color",
  "QR Background Color": "QR Background Color",
  "GENERATE QR": "GENERATE QR",
  "DOWNLOAD QR": "DOWNLOAD QR",
  "Details Submission" : "Details Submission",
  "Your restaurant successfully submitted for verification, once verified you can start adding menus and start selling": "Your restaurant successfully submitted for verification, once verified you can start adding menus and start selling",
  "Restaurant Details" : "Restaurant Details",
  "Restaurant Name EN" : "Restaurant Name EN",
  "Restaurant Name AR": "Restaurant Name AR",
  "Enter restaurant AR": "Enter restaurant AR",
  "Number of Tables": "Number of Tables",
  "Upload Logo": "Upload Logo",
  "Upload Banner": "Upload Banner",
  "State": "State",
  "Currency": "Currency",
  "Add currency": "Add currency",
  "Activate Tax": "Activate Tax",
  "City": "City",
  "Enter City": "Enter City",
  "Tax - VAT %": "Tax - VAT %",
  "Add vat % ex - 15": "Add vat % ex - 15",
  "UPDATE": "UPDATE",
  "My Plan": "My Plan",
  "Ending on": "Ending on",
  "UPGRADE": "UPGRADE",
  "Your request have been submitted, Soon you will get a call." : "Your request have been submitted, Soon you will get a call.",
  "Bank Details": "Bank Details",
  "Bank Name" : "Bank Name",
  "Add bank name": "Add bank name",
  "IBAN": "IBAN",
  "Loan information": "Loan information",
  "Company Name": "Company Name",
  "Add company name": "Add company name",
  "Your restaurant successfully submitted for verification, once verified you can start adding menus and start selling." : "Your restaurant successfully submitted for verification, once verified you can start adding menus and start selling.",
  "For more information contact @ admin@tablefrog.com OR +966-542909820": "For more information contact @ admin@tablefrog.com OR +966-542909820",
  "Restaurant Onboarding": "Restaurant Onboarding",
  "Restaurant Name" : "Restaurant Name",
  "Enter restaurant name": "Enter restaurant name",
  "Manager Name": "Manager Name",
  "Enter Manager name": "Enter Manager name",
  "Mobile No.": "Mobile No.",
  "Enter Mobile No.": "Enter Mobile No.",
  "Full Address": "Full Address",
  "Enter Full address": "Enter Full address",
  "Enter city name": "Enter city name",
  "Enter State name": "Enter State name",
  "Email": "Email",
  "Upload Cover Image": "Upload Cover Image",
  "Upload Business Document": "Upload Business Document",
  "Menus": "Menus",
  "Categories and items": "Categories and items",
  "Modifiers": "Modifiers",
  "Delete Item": "Delete Item",
  "Add Menu" : "Add Menu",
  "Menu Settings": "Menu Settings",
  "Menu Name" : "Menu Name",
  "Enter menu name": "Enter menu name",
  "Upload Image" : "Upload Image",
  "Choose Banner" : "Choose Banner",
  "NEXT" : "NEXT",
  "Default language": "Default language",
  "Allow Digital Payments": "Allow Digital Payments",
  "Allow Takeaway Orders": "Allow Takeaway Orders",
  "Payment Methods" : "Payment Methods",
  "Cash": "Cash",
  "Payment Terminal" : "Payment Terminal",
  "Credit Card": "Credit Card",
  "Mada" : "Mada",
  "Apple Pay": "Apple Pay",
  "Categories": "Categories",
  "Delete": "Delete",
  "Add Category": "Add Category",
  "Add Item" : "Add Item",
  "No dish available": "No dish available",
  "Add Dish" : "Add Dish",
  "Dish Detail": "Dish Detail",
  "Name": "Name",
  "Items": "Items",
  "Add Modifier" : "Add Modifier",
  "Edit Modifier": "Edit Modifier",
  "Delete Modifier": "Delete Modifier",
  "No modifiers available": "No modifiers available",
  "Add Modifier Group": "Add Modifier Group",
  "Enter name": "Enter name",
  "Name (Arabic)": "Name (Arabic)",
  "Enter name (arabic)": "Enter name (arabic)",
  "Is this required ?" : "Is this required ?",
  "required": "required",
  "optional": "optional",
  "How many items can the customer choose?": "How many items can the customer choose?",
  "Select minimum": "Select minimum",
  "Select maximum" : "Select maximum",
  "Name (AR)" : "Name (AR)",
  "Name (EN)": "Name (EN)",
  "Action": "Action",
  "Add": "Add",
  "SAVE": "SAVE",
  "Title": "Title",
  "Enter title": "Enter title",
  "title (Arabic)": "title (Arabic)",
  "Enter title (arabic)": "Enter title (arabic)",
  "Select Category": "Select Category",
  "Description": "Description",
  "Enter description":"Enter description",
  "Description (Arabic)" : "Description (Arabic)",
  "Enter Description ( Arabic )": "Enter Description ( Arabic )",
  "Add dish price": "Add dish price",
  "Calorie (per unit)": "Calorie (per unit)",
  "Add calories": "Add calories",
  "Product Image": "Product Image",
  "MODIFIERS" : "MODIFIERS",
  "Add modifier group": "Add modifier group",
  "+ Add new modifier group" : "+ Add new modifier group",
  "Customise Modifier": "Customise Modifier"
};

const t = (str) => {
  let lang = localStorage.getItem("language") || "en";
  return lang == "ar" ? translate[str] || str : str;
};

export default t;

